module.exports = {
	refreshTokens: [],
	users: [
		{
			id: "user1",
			email: "smol@gmail.com",
			password: "gao",
			seller: true,
			cart: {
				orders: [{id: "cart1", productId: "product1", amount: 1, unitPrice: 24000}],
			},
		},
		{
			id: "user2",
			email: "meow@gmail.com",
			password: "hi",
			seller: false,
			cart: {
				orders: [{id: "cart1", productId: "product1", amount: 1, unitPrice: 24000}],
			},
		},
		{
			id: "user3",
			email: "test@gmail.com",
			password: "test",
			seller: true,
			cart: {
				orders: [{id: "cart1", productId: "product1", amount: 1, unitPrice: 24000}],
			},
		},
	],
	products: [
		{
			id: "product1",
			sellerId: "user1",
			name: "Ice cream",
			unitPrice: 24000,
			amount: 10,
			bought: 2,
		},
		{
			id: "product2",
			sellerId: "user3",
			name: "Shit",
			unitPrice: 1000,
			amount: 999,
			bought: 2,
		},
		{
			id: "product3",
			sellerId: "user1",
			name: "Smol",
			unitPrice: 999999999999,
			amount: 1,
			bought: 1,
		},
		{
			id: "product4",
			sellerId: "user1",
			name: "Ice cream",
			unitPrice: 24000,
			amount: 10,
			bought: 2,
		},
		{
			id: "product5",
			sellerId: "user3",
			name: "Shit",
			unitPrice: 1000,
			amount: 999,
			bought: 2,
		},
		{
			id: "product6",
			sellerId: "user1",
			name: "Smol",
			unitPrice: 999999999999,
			amount: 1,
			bought: 1,
		},
		{
			id: "product7",
			sellerId: "user1",
			name: "Ice cream",
			unitPrice: 24000,
			amount: 10,
			bought: 2,
		},
		{
			id: "product8",
			sellerId: "user3",
			name: "Shit",
			unitPrice: 1000,
			amount: 999,
			bought: 2,
		},
		{
			id: "product9",
			sellerId: "user1",
			name: "Smol",
			unitPrice: 999999999999,
			amount: 1,
			bought: 1,
		},
		{
			id: "product10",
			sellerId: "user1",
			name: "Ice cream",
			unitPrice: 24000,
			amount: 10,
			bought: 2,
		},
		{
			id: "product11",
			sellerId: "user3",
			name: "Shit",
			unitPrice: 1000,
			amount: 999,
			bought: 2,
		},
		{
			id: "product12",
			sellerId: "user1",
			name: "Smol",
			unitPrice: 999999999999,
			amount: 1,
			bought: 1,
		},
		{
			id: "product13",
			sellerId: "user1",
			name: "Ice cream",
			unitPrice: 24000,
			amount: 10,
			bought: 2,
		},
		{
			id: "product14",
			sellerId: "user3",
			name: "Shit",
			unitPrice: 1000,
			amount: 999,
			bought: 2,
		},
		{
			id: "product15",
			sellerId: "user1",
			name: "Smol",
			unitPrice: 999999999999,
			amount: 1,
			bought: 1,
		},
		{
			id: "product16",
			sellerId: "user1",
			name: "Smol",
			unitPrice: 999999999999,
			amount: 1,
			bought: 1,
		},
	],
	orders: [
		{
			id: "order1",
			sellerId: "user1",
			buyerId: "user2",
			productId: "product1",
			amount: 2,
			status: "pending",
			address: "123 Happy street",
		},
		{
			id: "order2",
			sellerId: "user1",
			buyerId: "user2",
			productId: "product3",
			amount: 1,
			status: "confirmed",
			address: "234 Sad street",
		},
	],
};

/*
roles: ["buyer", "seller"]
status: "pending" | "confirmed" | "shipping" | "received"
*/
